package com.app.model;
// Generated 2016-3-27 16:06:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "library0321")
public class Book implements java.io.Serializable {

	private Integer realId;
	private String id;
	private String bookPic;
	private String bookName;
	private String autor;
	private String isbn;
	private String content;
	private String site;
	private String press;
	private String theme;
	private String picture;
	private String uid;
	private Date createTime;
	private Date deleteTime;
	private Integer status;

	public Book() {
	}

	public Book(String id, String bookPic, String bookName, String autor, String isbn, String content, String site,
			String press, String theme, String picture, String uid, Date createTime, Date deleteTime, Integer status) {
		this.id = id;
		this.bookPic = bookPic;
		this.bookName = bookName;
		this.autor = autor;
		this.isbn = isbn;
		this.content = content;
		this.site = site;
		this.press = press;
		this.theme = theme;
		this.picture = picture;
		this.uid = uid;
		this.createTime = createTime;
		this.deleteTime = deleteTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "real_id", unique = true, nullable = false)
	public Integer getRealId() {
		return this.realId;
	}

	public void setRealId(Integer realId) {
		this.realId = realId;
	}

	@Column(name = "id", length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "book_pic")
	public String getBookPic() {
		return this.bookPic;
	}

	public void setBookPic(String bookPic) {
		this.bookPic = bookPic;
	}

	@Column(name = "book_name", length = 20)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "autor", length = 20)
	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	@Column(name = "isbn", length = 40)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "site", length = 20)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "press", length = 20)
	public String getPress() {
		return this.press;
	}

	public void setPress(String press) {
		this.press = press;
	}

	@Column(name = "theme", length = 20)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "picture")
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "uid", length = 20)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_time", length = 19)
	public Date getDeleteTime() {
		return this.deleteTime;
	}

	public void setDeleteTime(Date deleteTime) {
		this.deleteTime = deleteTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
