package com.app.model;
// Generated 2016-3-27 16:06:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Borrow generated by hbm2java
 */
@Entity
@Table(name = "borrow", catalog = "library0321")
public class Borrow implements java.io.Serializable {

	private Integer id;
	private String username;
	private String bookId;
	private Date borrowTime;
	private Date willReturnTime;
	private Date returnTime;
	private Integer status;
	private String uid;
	
	@Transient
	private String bookName;

	public Borrow() {
	}

	public Borrow(String username, String bookId, Date borrowTime, Date willReturnTime, Date returnTime, Integer status,
			String uid) {
		this.username = username;
		this.bookId = bookId;
		this.borrowTime = borrowTime;
		this.willReturnTime = willReturnTime;
		this.returnTime = returnTime;
		this.status = status;
		this.uid = uid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "book_id", length = 10)
	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "borrow_time", length = 19)
	public Date getBorrowTime() {
		return this.borrowTime;
	}

	public void setBorrowTime(Date borrowTime) {
		this.borrowTime = borrowTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "will_return_time", length = 19)
	public Date getWillReturnTime() {
		return this.willReturnTime;
	}

	public void setWillReturnTime(Date willReturnTime) {
		this.willReturnTime = willReturnTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "return_time", length = 19)
	public Date getReturnTime() {
		return this.returnTime;
	}

	public void setReturnTime(Date returnTime) {
		this.returnTime = returnTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "uid", length = 20)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getBookName() {
		return bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

}
